<?php

// edit these elements to fit your data desire

$subreddit = "The_Donald";										// check exact spelling!
$fn_list = "list_The_Donald_top_all_2017-01-31_15-33.json";		// the file generated by the grab_list.php in your data_subreddit directory	
$filetype = ".csv";												// or .tab, .tsv etc.
$delimiter = ",";												// if you want a tab file, use \t (sign for tab)


// do not edit anything below this line
//-----------------------------------------------------

// basic script conf
date_default_timezone_set("UTC");
set_time_limit(3600*5);
ini_set("memory_limit","100M");
ini_set("error_reporting",1);

// set file paths
$workdir = getcwd();
$jsondir = $workdir . "/data_" . $subreddit . "/";
$fn_output = $workdir . "/" . preg_replace("/list_/","comments_", preg_replace("/\.json/", $filetype, $fn_list));

// get date from filename
$tmp = preg_match("/\d\d\d\d-\d\d-\d\d_\d\d-\d\d/",$fn_list,$out);
$timestamp = $out[0];

// read files in directory
$filelist = scandir($jsondir);

// open output file and create first line with stupid Excel UTF-8 BOM	
$fp = fopen($fn_output,"w");
$headers = array("\xEF\xBB\xBFpost_id","post_author","post_title","post_url","post_score","post_ups","post_downs","post_created","post_created_mysql","comment_id","comment_author","comment_permalink","comment_content","comment_nesting","comment_score","comment_downs","comment_ups","comment_created_unix","comment_created_mysql");
fputcsv($fp,$headers,$delimiter,"\"","\\");

// iterating over the file list
echo "\n\nreading files: ";

$counter = 0;
foreach($filelist as $fn) {

	if(!preg_match("/".$timestamp."/", $fn) || !preg_match("/thread_/", $fn)) { continue; }
	
	$fcontent = json_decode(file_get_contents($jsondir . $fn));
	$postdata = $fcontent[0]->data->children[0]->data;
	
	$depth = -1;
	
	// this function digs recursively into the thread structure
	processlisting($fcontent[1]->data->children,0,$postdata,$fp,$delimiter);
	
	echo $counter . " ";
	$counter++;
}

fclose($fn);

echo "\n\nfinished\n\n";



function processlisting($commentlist,$depth,$postdata,$fp,$delimiter) {
	
	$depth++;
	
	foreach($commentlist as $comment) {
		
		//print_r($comment); exit;
		
		if($comment->kind == "more") { continue; }
		
		$ln = array($postdata->name,
					$postdata->author,
					clean($postdata->title),
					"http://www.reddit.com" . $postdata->permalink,
					$postdata->score,
					$postdata->ups,
					$postdata->downs,
					$postdata->created,
					date("Y-m-d H:i:s",$postdata->created),
					$comment->data->name,
					$comment->data->author,
					"http://www.reddit.com" . $postdata->permalink . $comment->data->id,
					clean($comment->data->body),
					$depth,
					$comment->data->score,
					$comment->data->downs,
					$comment->data->ups,
					$comment->data->created,
					date("Y-m-d H:i:s",$comment->data->created));
		
		fputcsv($fp,$ln,$delimiter,"\"","\\");
		
		if($comment->data->replies != "") {
			
			processlisting($comment->data->replies->data->children,$depth,$postdata,$fp,$delimiter);
		}
	}
}


function clean($text) {
	
	$text = preg_replace("/[\n\t\r]/","", $text);
	
	return $text;
}


?>