<?

// edit these elements to fit your data desire

$subreddit = "The_Donald";										// check exact spelling!
$fn_list = "list_The_Donald_top_all_2017-01-31_15-33.json";		// the file generated by the grab_list.php in your data_subreddit directory	
$filetype = ".csv";												// or .tab, .tsv etc.
$delimiter = ",";												// if you want a tab file, use \t (sign for tab)


// do not edit anything below this line
//-----------------------------------------------------

// basic script conf
date_default_timezone_set("UTC");
set_time_limit(3600*5);
ini_set("memory_limit","100M");
ini_set("error_reporting",1);

// set file paths
$workdir = getcwd();
$jsondir = $workdir . "/data_" . $subreddit . "/";
$fn_output = $workdir . "/" . preg_replace("/\.json/", $filetype, $fn_list);

// get data from JSON file
$json = json_decode(file_get_contents($jsondir . $fn_list));

// open output file and create first line with stupid Excel UTF-8 BOM	
$fp = fopen($fn_output,"w");
$headers = array("\xEF\xBB\xBFid","author","title","score","ups","created","domain","url");
fputcsv($fp,$headers,$delimiter,"\"","\\");

// iterate over posts
foreach($json as $post) {
	$ln = array($post->data->id,$post->data->author,$post->data->title,$post->data->score,$post->data->ups,$post->data->created,$post->data->domain,preg_replace("/&amp;/", "&", $post->data->url));
	fputcsv($fp,$ln,$delimiter,"\"","\\");
}

fclose($fp);

echo "\n\nfinished\n\n";

?>